# Generated by Django 5.2.17 on 2026-10-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokercity', '0022_rename_monitoring_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='agent_contact_comment',
            field=models.CharField(blank=True, help_text='Agent Contact Comment', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='lead_reassigned_no',
            field=models.IntegerField(blank=True, help_text='Lead No', null=True),
        ),
    ]
