# Generated by Django 5.2.17 on 2026-10-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokercity', '0023_monitor_agent_contact_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='agent_assigned_duration',
            field=models.IntegerField(blank=True, help_text='Agent contact duration', null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='agent_reassigned_comment',
            field=models.CharField(blank=True, help_text='Agent Contact Comment', max_length=255, null=True),
        ),
    ]
