# Generated by Django 5.2.17 on 2026-10-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokercity', '0024_monitor_agent_assigned_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='agent_assigned_duration',
            field=models.CharField(blank=True, help_text='Agent contact duration', null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='agent_contact_duration',
            field=models.CharField(blank=True, help_text='Agent contact duration', null=True),
        ),
    ]
