--
-- PostgreSQL database dump
--

\restrict 7wAUWHN9oVdahlRyvHDkpvC2HHkXHWfYscZP6l6kRJ67wPWqHfiXHijy1M9OvCg

-- Dumped from database version 18.6 (Debian 18.6-1.pgdg12+2)
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: archive_brokercity_user
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO archive_brokercity_user;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: archive_brokercity_user
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: archive_brokercity_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO archive_brokercity_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: archive_brokercity_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO archive_brokercity_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: archive_brokercity_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO archive_brokercity_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: archive_brokercity_user
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO archive_brokercity_user;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: archive_brokercity_user
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO archive_brokercity_user;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: archive_brokercity_user
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO archive_brokercity_user;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brokercity_account; Type: TABLE; Schema: public; Owner: archive_brokercity_user
--

CREATE TABLE public.brokercity_account (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    type character varying(10) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    category_id bigint NOT NULL
);


ALTER TABLE public.brokercity_account OWNER TO archive_brokercity_user;

--
-- Name: brokercity_account_id_seq; Type: SEQUENCE; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE public.brokercity_account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.brokercity_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brokercity_accountcategory; Type: TABLE; Schema: public; Owner: archive_brokercity_user
--

CREATE TABLE public.brokercity_accountcategory (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.brokercity_accountcategory OWNER TO archive_brokercity_user;

--
-- Name: brokercity_accountcategory_id_seq; Type: SEQUENCE; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE public.brokercity_accountcategory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.brokercity_accountcategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brokercity_agent; Type: TABLE; Schema: public; Owner: archive_brokercity_user
--

CREATE TABLE public.brokercity_agent (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    department character varying(100) NOT NULL,
    phone_number character varying(15) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.brokercity_agent OWNER TO archive_brokercity_user;

--
-- Name: brokercity_agent_id_seq; Type: SEQUENCE; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE public.brokercity_agent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.brokercity_agent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brokercity_bank; Type: TABLE; Schema: public; Owner: archive_brokercity_user
--

CREATE TABLE public.brokercity_bank (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    balance numeric(15,2) NOT NULL,
    balance_opening numeric(15,2) NOT NULL,
    currency character varying(3) NOT NULL,
    account_number character varying(50),
    iban character varying(34),
    swift_code character varying(11),
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    notes text
);


ALTER TABLE public.brokercity_bank OWNER TO archive_brokercity_user;

--
-- Name: brokercity_bank_id_seq; Type: SEQUENCE; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE public.brokercity_bank ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.brokercity_bank_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brokercity_building; Type: TABLE; Schema: public; Owner: archive_brokercity_user
--

CREATE TABLE public.brokercity_building (
    id bigint NOT NULL,
    name character varying(100),
    type character varying(100),
    status character varying(100),
    area character varying(100),
    location character varying(100),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    owner_id bigint
);


ALTER TABLE public.brokercity_building OWNER TO archive_brokercity_user;

--
-- Name: brokercity_building_id_seq; Type: SEQUENCE; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE public.brokercity_building ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.brokercity_building_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brokercity_cashbox; Type: TABLE; Schema: public; Owner: archive_brokercity_user
--

CREATE TABLE public.brokercity_cashbox (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    balance_opening numeric(15,2) NOT NULL,
    balance numeric(15,2) NOT NULL,
    currency character varying(3) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    notes text
);


ALTER TABLE public.brokercity_cashbox OWNER TO archive_brokercity_user;

--
-- Name: brokercity_cashbox_id_seq; Type: SEQUENCE; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE public.brokercity_cashbox ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.brokercity_cashbox_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brokercity_customer; Type: TABLE; Schema: public; Owner: archive_brokercity_user
--

CREATE TABLE public.brokercity_customer (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    phone_number character varying(15) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.brokercity_customer OWNER TO archive_brokercity_user;

--
-- Name: brokercity_customer_id_seq; Type: SEQUENCE; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE public.brokercity_customer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.brokercity_customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brokercity_developer; Type: TABLE; Schema: public; Owner: archive_brokercity_user
--

CREATE TABLE public.brokercity_developer (
    id bigint NOT NULL,
    name character varying(100),
    phone character varying(100),
    type character varying(100),
    email character varying(100),
    "Registered" boolean
);


ALTER TABLE public.brokercity_developer OWNER TO archive_brokercity_user;

--
-- Name: brokercity_developer_id_seq; Type: SEQUENCE; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE public.brokercity_developer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.brokercity_developer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brokercity_monitor; Type: TABLE; Schema: public; Owner: archive_brokercity_user
--

CREATE TABLE public.brokercity_monitor (
    id bigint CONSTRAINT brokercity_monitoring_id_not_null NOT NULL,
    date date,
    month character varying(20),
    lead_no integer,
    agent character varying(100),
    agent_lead_no integer,
    agent_contact_duration integer,
    draws double precision,
    draws_no integer,
    draws_cause character varying(255),
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);


ALTER TABLE public.brokercity_monitor OWNER TO archive_brokercity_user;

--
-- Name: brokercity_monitoring_id_seq; Type: SEQUENCE; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE public.brokercity_monitor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.brokercity_monitoring_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brokercity_offersale; Type: TABLE; Schema: public; Owner: archive_brokercity_user
--

CREATE TABLE public.brokercity_offersale (
    id bigint NOT NULL,
    reference_no character varying(100),
    date date,
    recipient_name character varying(200),
    project character varying(100),
    unit_no character varying(100),
    estimated_completion_date character varying(100),
    listing_title character varying(200),
    unit_type character varying(100),
    unit_model character varying(100),
    bedrooms character varying(50),
    unit_position character varying(100),
    unit_grade character varying(50),
    unit_note character varying(100),
    plot_area character varying(100),
    gross_saleable_area character varying(100),
    total_area character varying(100),
    internal_area character varying(100),
    terrace_area character varying(100),
    image character varying(100),
    image_url character varying(200),
    currency character varying(10) NOT NULL,
    base_price numeric(15,2),
    selling_price numeric(15,2),
    premium_amount numeric(15,2),
    noc_fee numeric(15,2),
    transfer_fee numeric(15,2),
    agency_fee numeric(15,2),
    owner_paid_total numeric(15,2),
    buyer_total numeric(15,2),
    promotion character varying(200),
    waiver character varying(100),
    waiver_second character varying(100),
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);


ALTER TABLE public.brokercity_offersale OWNER TO archive_brokercity_user;

--
-- Name: brokercity_offersale_id_seq; Type: SEQUENCE; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE public.brokercity_offersale ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.brokercity_offersale_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brokercity_owner; Type: TABLE; Schema: public; Owner: archive_brokercity_user
--

CREATE TABLE public.brokercity_owner (
    id bigint NOT NULL,
    name character varying(100),
    phone character varying(100),
    address character varying(255),
    balance numeric(15,2),
    balance_opening numeric(15,2),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.brokercity_owner OWNER TO archive_brokercity_user;

--
-- Name: brokercity_owner_id_seq; Type: SEQUENCE; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE public.brokercity_owner ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.brokercity_owner_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brokercity_paymentplan; Type: TABLE; Schema: public; Owner: archive_brokercity_user
--

CREATE TABLE public.brokercity_paymentplan (
    id bigint NOT NULL,
    installments jsonb NOT NULL,
    base_price numeric(15,2),
    final_price numeric(15,2),
    adm_fee numeric(15,2),
    adm_admin_fee numeric(15,2),
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    unit_no character varying(100)
);


ALTER TABLE public.brokercity_paymentplan OWNER TO archive_brokercity_user;

--
-- Name: brokercity_paymentplan_id_seq; Type: SEQUENCE; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE public.brokercity_paymentplan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.brokercity_paymentplan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brokercity_profile; Type: TABLE; Schema: public; Owner: archive_brokercity_user
--

CREATE TABLE public.brokercity_profile (
    id bigint NOT NULL,
    image character varying(100),
    role character varying(10) NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.brokercity_profile OWNER TO archive_brokercity_user;

--
-- Name: brokercity_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE public.brokercity_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.brokercity_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brokercity_rental; Type: TABLE; Schema: public; Owner: archive_brokercity_user
--

CREATE TABLE public.brokercity_rental (
    id bigint NOT NULL,
    name character varying(100),
    nationality character varying(100),
    phone_1 character varying(100),
    phone_2 character varying(100),
    id_number character varying(100),
    email character varying(100),
    insurance_balance numeric(15,2),
    balance numeric(15,2)
);


ALTER TABLE public.brokercity_rental OWNER TO archive_brokercity_user;

--
-- Name: brokercity_rental_id_seq; Type: SEQUENCE; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE public.brokercity_rental ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.brokercity_rental_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brokercity_slider; Type: TABLE; Schema: public; Owner: archive_brokercity_user
--

CREATE TABLE public.brokercity_slider (
    id bigint NOT NULL,
    description text,
    image character varying(100),
    apartments character varying(100),
    area_from character varying(100),
    booking_fee character varying(100),
    developer character varying(100),
    duplexes character varying(100),
    handover character varying(100),
    image_1 character varying(100),
    image_2 character varying(100),
    image_3 character varying(100),
    image_4 character varying(100),
    license_number character varying(100),
    location character varying(100),
    name character varying(200),
    payment_plan character varying(100),
    penthouses character varying(100),
    project_number character varying(100),
    starting_price character varying(100),
    studios character varying(100),
    townhouses character varying(100)
);


ALTER TABLE public.brokercity_slider OWNER TO archive_brokercity_user;

--
-- Name: brokercity_slider_id_seq; Type: SEQUENCE; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE public.brokercity_slider ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.brokercity_slider_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brokercity_transaction; Type: TABLE; Schema: public; Owner: archive_brokercity_user
--

CREATE TABLE public.brokercity_transaction (
    id bigint NOT NULL,
    transaction_no character varying(20) NOT NULL,
    transaction_date date NOT NULL,
    type character varying(10) NOT NULL,
    amount numeric(12,2) NOT NULL,
    amount_deposit numeric(12,2) NOT NULL,
    amount_withdraw numeric(12,2) NOT NULL,
    amount_to_arabic character varying(255),
    amount_to_english character varying(255),
    currency character varying(10) NOT NULL,
    payment_method character varying(10) NOT NULL,
    has_check boolean NOT NULL,
    check_no character varying(50) NOT NULL,
    check_bank character varying(100) NOT NULL,
    check_date date NOT NULL,
    statement character varying(100) NOT NULL,
    person_receipt character varying(100),
    person_deliver character varying(100) NOT NULL,
    user_signature text,
    manager_signature text,
    second_person_signature text,
    has_document boolean NOT NULL,
    document character varying(100),
    document_no character varying(50),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    notes text,
    account_from character varying(255) NOT NULL,
    account_to character varying(255) NOT NULL,
    bank_id bigint,
    cashbox_id bigint,
    transaction_user_id integer,
    subtotal numeric(12,2) NOT NULL,
    vat numeric(12,2) NOT NULL
);


ALTER TABLE public.brokercity_transaction OWNER TO archive_brokercity_user;

--
-- Name: brokercity_transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE public.brokercity_transaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.brokercity_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brokercity_unit; Type: TABLE; Schema: public; Owner: archive_brokercity_user
--

CREATE TABLE public.brokercity_unit (
    id bigint NOT NULL,
    name character varying(100),
    type character varying(100),
    status character varying(100),
    price numeric(15,2),
    bedrooms integer,
    bathrooms integer,
    has_parking boolean,
    parking integer,
    furnished boolean,
    unfurnished boolean,
    image_1 character varying(100),
    image_2 character varying(100),
    image_3 character varying(100),
    image_4 character varying(100),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    category_id bigint,
    area character varying(100),
    floor character varying(100)
);


ALTER TABLE public.brokercity_unit OWNER TO archive_brokercity_user;

--
-- Name: brokercity_unit_id_seq; Type: SEQUENCE; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE public.brokercity_unit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.brokercity_unit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brokercity_whatsappmessage; Type: TABLE; Schema: public; Owner: archive_brokercity_user
--

CREATE TABLE public.brokercity_whatsappmessage (
    id bigint NOT NULL,
    to_number character varying(20) NOT NULL,
    message_body text NOT NULL,
    status character varying(10) NOT NULL,
    twilio_sid character varying(50),
    error_message text,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.brokercity_whatsappmessage OWNER TO archive_brokercity_user;

--
-- Name: brokercity_whatsappmessage_id_seq; Type: SEQUENCE; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE public.brokercity_whatsappmessage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.brokercity_whatsappmessage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: archive_brokercity_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO archive_brokercity_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: archive_brokercity_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO archive_brokercity_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: archive_brokercity_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO archive_brokercity_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: archive_brokercity_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO archive_brokercity_user;

--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: archive_brokercity_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: archive_brokercity_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: archive_brokercity_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add account category	7	add_accountcategory
26	Can change account category	7	change_accountcategory
27	Can delete account category	7	delete_accountcategory
28	Can view account category	7	view_accountcategory
29	Can add bank	8	add_bank
30	Can change bank	8	change_bank
31	Can delete bank	8	delete_bank
32	Can view bank	8	view_bank
33	Can add cash box	9	add_cashbox
34	Can change cash box	9	change_cashbox
35	Can delete cash box	9	delete_cashbox
36	Can view cash box	9	view_cashbox
37	Can add account	10	add_account
38	Can change account	10	change_account
39	Can delete account	10	delete_account
40	Can view account	10	view_account
41	Can add profile	11	add_profile
42	Can change profile	11	change_profile
43	Can delete profile	11	delete_profile
44	Can view profile	11	view_profile
45	Can add transaction	12	add_transaction
46	Can change transaction	12	change_transaction
47	Can delete transaction	12	delete_transaction
48	Can view transaction	12	view_transaction
49	Can add customer	13	add_customer
50	Can change customer	13	change_customer
51	Can delete customer	13	delete_customer
52	Can view customer	13	view_customer
53	Can add whats app message	14	add_whatsappmessage
54	Can change whats app message	14	change_whatsappmessage
55	Can delete whats app message	14	delete_whatsappmessage
56	Can view whats app message	14	view_whatsappmessage
57	Can add monitoring	15	add_monitoring
58	Can change monitoring	15	change_monitoring
59	Can delete monitoring	15	delete_monitoring
60	Can view monitoring	15	view_monitoring
61	Can add agent	16	add_agent
62	Can change agent	16	change_agent
63	Can delete agent	16	delete_agent
64	Can view agent	16	view_agent
65	Can add category	17	add_category
66	Can change category	17	change_category
67	Can delete category	17	delete_category
68	Can view category	17	view_category
69	Can add owner	18	add_owner
70	Can change owner	18	change_owner
71	Can delete owner	18	delete_owner
72	Can view owner	18	view_owner
73	Can add unit	19	add_unit
74	Can change unit	19	change_unit
75	Can delete unit	19	delete_unit
76	Can view unit	19	view_unit
77	Can add building	20	add_building
78	Can change building	20	change_building
79	Can delete building	20	delete_building
80	Can view building	20	view_building
81	Can add slider	21	add_slider
82	Can change slider	21	change_slider
83	Can delete slider	21	delete_slider
84	Can view slider	21	view_slider
85	Can add rental	22	add_rental
86	Can change rental	22	change_rental
87	Can delete rental	22	delete_rental
88	Can view rental	22	view_rental
89	Can add developer	23	add_developer
90	Can change developer	23	change_developer
91	Can delete developer	23	delete_developer
92	Can view developer	23	view_developer
93	Can add Payment Plan	24	add_paymentplan
94	Can change Payment Plan	24	change_paymentplan
95	Can delete Payment Plan	24	delete_paymentplan
96	Can view Payment Plan	24	view_paymentplan
97	Can add offersale	25	add_offersale
98	Can change offersale	25	change_offersale
99	Can delete offersale	25	delete_offersale
100	Can view offersale	25	view_offersale
101	Can add monitor	15	add_monitor
102	Can change monitor	15	change_monitor
103	Can delete monitor	15	delete_monitor
104	Can view monitor	15	view_monitor
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: archive_brokercity_user
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
2	pbkdf2_sha256$1000000$fKegoQB5AQSWuwaZFTSNuF$l2s2tF94yAIQMhUvssVwd/WLUT+Z3Y5lwTOPtoN0Wys=	\N	f	ghada			ghada@example.com	f	t	2026-08-30 06:10:56.679235+00
4	pbkdf2_sha256$1000000$MOgAaS3TMgRM7hgYDe1L5N$4uQ9Ob+3A4fOCpq3fhJEGPa2rnNunJkbddVtqL9Jp74=	\N	f	muhammed			muhammed@example.com	f	t	2026-09-03 08:56:43.734667+00
5	pbkdf2_sha256$1000000$vxjt0PAPGQOImN0UyPePE3$cxpedgTaR4Rnj3z/EKBa5XhlmlrrbZivhxe/hfBzJUE=	\N	f	abubakr			abubakr@example.com	f	t	2026-09-03 09:24:17.598003+00
1	pbkdf2_sha256$1000000$4hzLTd93Jj8QOXMGEB8tFz$sMe8KVtaH8KkPWYN9s+EOpKrvSAgu8E31kaDvXMERDU=	\N	f	manager			manager@example.com	f	t	2026-08-30 06:09:31.961739+00
3	pbkdf2_sha256$1000000$3cx70h277L3YC71tpDTFLf$eaH4byUc9KqgCyE9nsr3ch1obk8EMn1qyolMa0KfZVE=	\N	f	muhsin			muhsin@example.com	f	t	2026-09-03 08:55:49.610468+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: archive_brokercity_user
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: archive_brokercity_user
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: brokercity_account; Type: TABLE DATA; Schema: public; Owner: archive_brokercity_user
--

COPY public.brokercity_account (id, name, type, created_at, updated_at, category_id) FROM stdin;
1	مصروفات ضيافة	expenses	2026-08-31 08:33:56.00812+00	2026-08-31 08:33:56.00812+00	1
2	سلفيات الموظفين	expenses	2026-08-31 08:34:23.263182+00	2026-08-31 08:34:23.263182+00	1
3	القيم الايجارية	revenues	2026-08-31 08:34:40.031899+00	2026-08-31 08:34:40.031899+00	2
4	ديلات محسن	revenues	2026-09-25 15:54:30.263733+00	2026-09-25 15:54:30.263733+00	2
\.


--
-- Data for Name: brokercity_accountcategory; Type: TABLE DATA; Schema: public; Owner: archive_brokercity_user
--

COPY public.brokercity_accountcategory (id, name, created_at, updated_at) FROM stdin;
1	مصروفات	2026-08-31 08:32:28.2962+00	2026-08-31 08:32:28.2962+00
2	ايرادات	2026-08-31 08:32:35.811626+00	2026-08-31 08:32:35.811626+00
\.


--
-- Data for Name: brokercity_agent; Type: TABLE DATA; Schema: public; Owner: archive_brokercity_user
--

COPY public.brokercity_agent (id, name, department, phone_number, created_at) FROM stdin;
3	Zakam Ahmed	Agent	+123122312123	2026-09-15 13:18:08.769666+00
4	Amr Mohammed	Agent	+123121223123	2026-09-15 13:19:32.262292+00
5	Test Account Sultan	Agent	+123101010110	2026-09-15 13:21:02.067653+00
6	Test Account Walla	Agent	+101101010123	2026-09-15 13:21:42.720336+00
7	Rana Ahmed	Agent	+101010123	2026-09-15 13:22:12.326506+00
8	Nora	Agent	+111101010123	2026-09-15 13:23:36.52157+00
\.


--
-- Data for Name: brokercity_bank; Type: TABLE DATA; Schema: public; Owner: archive_brokercity_user
--

COPY public.brokercity_bank (id, name, balance, balance_opening, currency, account_number, iban, swift_code, is_active, created_at, updated_at, notes) FROM stdin;
1	مصرف أبوظبي الاسلامي	0.00	0.00	AED				t	2026-08-31 08:26:04.735924+00	2026-08-31 08:26:04.735924+00	
2	ADIB	0.00	0.00	AED				t	2026-09-28 11:33:56.079326+00	2026-09-28 11:33:56.079343+00	
\.


--
-- Data for Name: brokercity_building; Type: TABLE DATA; Schema: public; Owner: archive_brokercity_user
--

COPY public.brokercity_building (id, name, type, status, area, location, created_at, updated_at, owner_id) FROM stdin;
1	بناية أحمد البريكي	building	residential	أبوظبي	ال نهيان	2026-09-18 07:13:59.390627+00	2026-09-18 07:13:59.390627+00	2
2	فيلا رقم 70	vila	residential	بني ياس	ابوظبي بني ياس	2026-10-01 14:20:32.343709+00	2026-10-01 14:20:32.343709+00	3
\.


--
-- Data for Name: brokercity_cashbox; Type: TABLE DATA; Schema: public; Owner: archive_brokercity_user
--

COPY public.brokercity_cashbox (id, name, balance_opening, balance, currency, is_active, created_at, updated_at, notes) FROM stdin;
1	خزينة بروكر سيتي	0.00	0.00	SAR	t	2026-08-31 08:20:07.593626+00	2026-08-31 08:20:07.593626+00	\N
2	خزينة رقم 2	0.00	0.00	SAR	t	2026-09-01 11:29:27.767873+00	2026-09-01 11:29:27.767873+00	\N
3	خزينة احمد البريكي	0.00	0.00	SAR	t	2026-09-10 14:21:43.16564+00	2026-09-10 14:21:43.16566+00	\N
\.


--
-- Data for Name: brokercity_customer; Type: TABLE DATA; Schema: public; Owner: archive_brokercity_user
--

COPY public.brokercity_customer (id, name, phone_number, created_at) FROM stdin;
\.


--
-- Data for Name: brokercity_developer; Type: TABLE DATA; Schema: public; Owner: archive_brokercity_user
--

COPY public.brokercity_developer (id, name, phone, type, email, "Registered") FROM stdin;
12	Urban Capital Development		مطور عقاري - شركة		\N
11	One Development | Abu Dhabi Showroom		مطور عقاري - شركة		\N
10	Providential Properties Management Abu Dhabi		تطوير وادارة عقارية - شركة		\N
9	Arabesco Asset Management		تطوير وادارة عقارية - شركة		\N
8	Samana Developers - Abu Dhabi		مطور عقاري - شركة		\N
7	Deyaar Development PJSC (Abu Dhabi Branch)		مطور عقاري - شركة		\N
6	Emaar Sales Centre - Abu Dhabi - Emaar		مطور عقاري - شركة		\N
5	Eagle Hills Properties LLC - Abu Dhabi		مطور عقاري - شركة		\N
4	Baraka Real Estate Development		مطور عقاري - شركة		\N
3	Reportage Properties LLC		مطور عقاري - شركة		\N
\.


--
-- Data for Name: brokercity_monitor; Type: TABLE DATA; Schema: public; Owner: archive_brokercity_user
--

COPY public.brokercity_monitor (id, date, month, lead_no, agent, agent_lead_no, agent_contact_duration, draws, draws_no, draws_cause, created_at, updated_at) FROM stdin;
3	2026-10-03	October	\N	Abdalla	44	60	\N	\N	\N	2026-10-03 10:56:10.902884+00	2026-10-03 10:56:10.902884+00
4	2026-10-03	October	\N	Ahmed Rezg	32	60	\N	1	عدم التواصل مع العميل   مع وضع العميل تحت مرحلة تم التواصل	2026-10-03 12:02:54.701936+00	2026-10-03 12:02:54.701936+00
\.


--
-- Data for Name: brokercity_offersale; Type: TABLE DATA; Schema: public; Owner: archive_brokercity_user
--

COPY public.brokercity_offersale (id, reference_no, date, recipient_name, project, unit_no, estimated_completion_date, listing_title, unit_type, unit_model, bedrooms, unit_position, unit_grade, unit_note, plot_area, gross_saleable_area, total_area, internal_area, terrace_area, image, image_url, currency, base_price, selling_price, premium_amount, noc_fee, transfer_fee, agency_fee, owner_paid_total, buyer_total, promotion, waiver, waiver_second, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: brokercity_owner; Type: TABLE DATA; Schema: public; Owner: archive_brokercity_user
--

COPY public.brokercity_owner (id, name, phone, address, balance, balance_opening, created_at, updated_at) FROM stdin;
1	حاتم عبدالله طه	0503034312	-	35000.00	25000.00	2026-09-17 09:03:37.664735+00	2026-09-17 09:04:05.453627+00
2	احمد البريكي	0502030123	أبوظبي ال نهيان	0.00	0.00	2026-09-18 07:12:38.772185+00	2026-09-18 07:12:38.772185+00
3	بدرية العريفي	0502000195	بني ياس 6/2  فيلا رقم 15	0.00	0.00	2026-10-01 14:17:55.333963+00	2026-10-01 14:17:55.333963+00
\.


--
-- Data for Name: brokercity_paymentplan; Type: TABLE DATA; Schema: public; Owner: archive_brokercity_user
--

COPY public.brokercity_paymentplan (id, installments, base_price, final_price, adm_fee, adm_admin_fee, created_at, updated_at, unit_no) FROM stdin;
\.


--
-- Data for Name: brokercity_profile; Type: TABLE DATA; Schema: public; Owner: archive_brokercity_user
--

COPY public.brokercity_profile (id, image, role, user_id) FROM stdin;
1		user	1
2		user	2
3		user	3
4		user	4
5		user	5
\.


--
-- Data for Name: brokercity_rental; Type: TABLE DATA; Schema: public; Owner: archive_brokercity_user
--

COPY public.brokercity_rental (id, name, nationality, phone_1, phone_2, id_number, email, insurance_balance, balance) FROM stdin;
1	حاتم عبدالله طه محمد	السودان	0503034312	0503034312	0123456789	hatim@example.com	0.00	0.00
2	صفاء	الاردن	052000101	0503034312	0123456789	7atim1000@gmail.com	0.00	0.00
\.


--
-- Data for Name: brokercity_slider; Type: TABLE DATA; Schema: public; Owner: archive_brokercity_user
--

COPY public.brokercity_slider (id, description, image, apartments, area_from, booking_fee, developer, duplexes, handover, image_1, image_2, image_3, image_4, license_number, location, name, payment_plan, penthouses, project_number, starting_price, studios, townhouses) FROM stdin;
7	\N	slider/b0e8bb29-9d1e-4756-a62e-0b8ba564baaa_eu5k8Wn.jpeg	\N	\N	\N	\N	\N	\N					\N	\N	The Beach House Fahid - Wellness Living by the Sea	65/35	\N	\N	1.8M	\N	\N
6	\N	slider/2cb1a58f-f01f-4ee2-bf2b-0ef1445c0f71_V0ytQTG.jpeg	\N	\N	\N	\N	\N	\N					\N	\N	Nobu Residences Abu Dhabi - Branded Residences on Saadiyat Island	Easy	\N	\N	7.3M	\N	\N
8	\N	slider/1th_Fy6ZEYs.jpeg	\N	\N	10%	ALDAR	\N	Q2 2029					202402273451	Fahid Island	New Project by Aldar Properties on Fahid Island - Fahid Beach Residences	65/35%	\N	20250000573463	3.5M	\N	\N
\.


--
-- Data for Name: brokercity_transaction; Type: TABLE DATA; Schema: public; Owner: archive_brokercity_user
--

COPY public.brokercity_transaction (id, transaction_no, transaction_date, type, amount, amount_deposit, amount_withdraw, amount_to_arabic, amount_to_english, currency, payment_method, has_check, check_no, check_bank, check_date, statement, person_receipt, person_deliver, user_signature, manager_signature, second_person_signature, has_document, document, document_no, created_at, updated_at, notes, account_from, account_to, bank_id, cashbox_id, transaction_user_id, subtotal, vat) FROM stdin;
97	101-1	2026-09-23	deposit	56700.00	56700.00	0.00	56700.00 (بالعربية)	56700.00 (in English)	AED	banks	f			2024-01-01	صرف العمولة الخاصة بعملية بيع الوحدة رقم 78 في مشروع بوابة الشرق	\N	سعاد محمد سلمان السويدي				f			2026-09-28 12:56:13.28814+00	2026-10-01 08:52:58.332393+00		الايرادات	ADIB	2	\N	1	0.00	0.00
\.


--
-- Data for Name: brokercity_unit; Type: TABLE DATA; Schema: public; Owner: archive_brokercity_user
--

COPY public.brokercity_unit (id, name, type, status, price, bedrooms, bathrooms, has_parking, parking, furnished, unfurnished, image_1, image_2, image_3, image_4, created_at, updated_at, category_id, area, floor) FROM stdin;
2	شقة 101	apartment	available	5500.00	2	3	t	\N	f	t					2026-09-18 07:57:39.060702+00	2026-09-23 10:59:06.438881+00	1	أبوظبي	second
3	شقة Roof-1	apartment	occupied	3500.00	2	2	f	\N	f	t					2026-10-01 14:24:09.451211+00	2026-10-01 14:24:09.451211+00	2	بني ياس	second
\.


--
-- Data for Name: brokercity_whatsappmessage; Type: TABLE DATA; Schema: public; Owner: archive_brokercity_user
--

COPY public.brokercity_whatsappmessage (id, to_number, message_body, status, twilio_sid, error_message, created_at) FROM stdin;
1	+971503034312	Hello! This is a message from our system.	pending	\N	\N	2026-09-08 12:37:52.44622+00
2	+971503034312	Hello! This is a message from our system.	sent	SM41eda078fb8ca359ef88dff374250b6e	\N	2026-09-08 12:40:58.996826+00
3	+971503034312	Hello! This is a message from our system.	sent	SMa534aaed07e04583ca70f7b198ab3dff	\N	2026-09-08 12:46:08.613322+00
4	+971503034312	Broker City Properties. Your integrated digital real estate platform	sent	SM185e481392923ee82d08602a3ba40aff	\N	2026-09-08 12:49:18.838351+00
5	+971503034312	🏙️ *Broker City Properties*\nYour integrated digital real estate platform	sent	SM0565a3c584da52f0b34a27d3c26c3122	\N	2026-09-08 12:52:11.457243+00
6	+971503034312	🏙️ *Broker City Properties*\nYour integrated digital real estate platform	sent	SMed8069bc2a721634d9da7986eac2cc7f	\N	2026-09-08 13:11:22.875868+00
7	+971503034312	🏙️ *Broker City Properties*\nYour integrated digital real estate platform	sent	SM74314db185871921b2cac392bea242ec	\N	2026-09-08 13:16:30.214737+00
8	+971503034312	🏙️ *Broker City Properties*\nYour integrated digital real estate platform	sent	SMda9e403ff4ab71a6afc601d2910ef88b	\N	2026-09-08 13:20:44.212839+00
9	+971503034312	🏙️ *بروكر سيتي العقارية*\nمنصتك العقاريةالرقميةالمتكاملة	sent	SM2c6e8601d798a43b6c41ff6707bca935	\N	2026-09-08 13:23:25.633037+00
10	+971503034312	🏙️ *بروكر سيتي العقارية*\nمنصتك العقارية الرقمية المتكاملة	sent	SM6b37905df4a5ecee4281cb17a7118653	\N	2026-09-08 13:38:14.721064+00
11	+971503034312	🏙️ *بروكر سيتي العقارية*\nمنصتك العقارية الرقمية المتكاملة	sent	SMa291135b536fa4c554a2b16e81c39047	\N	2026-09-08 14:22:09.53629+00
12	+971503034312	🏙️ *بروكر سيتي العقارية*\nمنصتك العقارية الرقمية المتكاملة	sent	SM1995911e53e08e4e6df67d719f70fd6e	\N	2026-09-09 05:41:21.009506+00
13	+971503034312	🏙️ *بروكر سيتي العقارية*\nمنصتك العقارية الرقمية المتكاملة	sent	SM0d31840ccdced435124ee11ad271d071	\N	2026-09-09 14:05:52.613232+00
14	+971503034312	🏙️ *بروكر سيتي العقارية*\nمنصتك العقارية الرقمية المتكاملة	sent	SM097e9ec19424eefd868f19d79fe7a4c9	\N	2026-09-09 14:06:43.854315+00
15	+971503034312	🏙️ *بروكر سيتي العقارية*\nمنصتك العقارية الرقمية المتكاملة	sent	SMa10b1a6480589c20fa5c871774907ca6	\N	2026-09-09 14:07:43.821583+00
16	+971503034312	🏙️ *بروكر سيتي العقارية*\nمنصتك العقارية الرقمية المتكاملة	sent	SM10f663ad9c03672ff4e243facd5f36e3	\N	2026-09-09 14:08:45.129134+00
17	+971503034312	🏙️ *بروكر سيتي العقارية*\nمنصتك العقارية الرقمية المتكاملة	sent	SMdc276dc0de8b8075cb5f2936cd2b210b	\N	2026-09-09 19:15:53.7834+00
18	+971503034312	🏙️ *بروكر سيتي العقارية*\nمنصتك العقارية الرقمية المتكاملة	sent	SM5d9d4992f104d08be504159c97755a04	\N	2026-09-10 09:41:44.830891+00
19	+971503034312	🏙️ *بروكر سيتي العقارية*\nمنصتك العقارية الرقمية المتكاملة	sent	SM67044a23edff61c8099e0b78357e178c	\N	2026-09-10 09:44:21.061982+00
20	+971503034312	🏙️ *بروكر سيتي العقارية*\nمنصتك العقارية الرقمية المتكاملة	sent	SM718888a07a21ab93b2aeac2d6c830344	\N	2026-09-10 09:46:41.809237+00
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: archive_brokercity_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: archive_brokercity_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	brokercity	accountcategory
8	brokercity	bank
9	brokercity	cashbox
10	brokercity	account
11	brokercity	profile
12	brokercity	transaction
13	brokercity	customer
14	brokercity	whatsappmessage
16	brokercity	agent
17	brokercity	category
18	brokercity	owner
19	brokercity	unit
20	brokercity	building
21	brokercity	slider
22	brokercity	rental
23	brokercity	developer
24	brokercity	paymentplan
25	brokercity	offersale
15	brokercity	monitor
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: archive_brokercity_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-08-30 05:32:27.391819+00
2	auth	0001_initial	2026-08-30 05:32:33.645593+00
3	admin	0001_initial	2026-08-30 05:32:35.315832+00
4	admin	0002_logentry_remove_auto_add	2026-08-30 05:32:35.545712+00
5	admin	0003_logentry_add_action_flag_choices	2026-08-30 05:32:36.331731+00
6	contenttypes	0002_remove_content_type_name	2026-08-30 05:32:37.737097+00
7	auth	0002_alter_permission_name_max_length	2026-08-30 05:32:38.576524+00
8	auth	0003_alter_user_email_max_length	2026-08-30 05:32:39.408457+00
9	auth	0004_alter_user_username_opts	2026-08-30 05:32:39.826812+00
10	auth	0005_alter_user_last_login_null	2026-08-30 05:32:40.869204+00
11	auth	0006_require_contenttypes_0002	2026-08-30 05:32:41.285691+00
12	auth	0007_alter_validators_add_error_messages	2026-08-30 05:32:41.914147+00
13	auth	0008_alter_user_username_max_length	2026-08-30 05:32:42.950589+00
14	auth	0009_alter_user_last_name_max_length	2026-08-30 05:32:43.784919+00
15	auth	0010_alter_group_name_max_length	2026-08-30 05:32:44.619359+00
16	auth	0011_update_proxy_permissions	2026-08-30 05:32:45.035289+00
17	auth	0012_alter_user_first_name_max_length	2026-08-30 05:32:46.081261+00
18	brokercity	0001_initial	2026-08-30 05:32:51.499222+00
19	sessions	0001_initial	2026-08-30 05:32:52.769433+00
20	brokercity	0002_alter_transaction_account_from_and_more	2026-08-31 09:27:11.591378+00
21	brokercity	0003_alter_transaction_amount_to_arabic_and_more	2026-08-31 09:42:36.883298+00
22	brokercity	0004_alter_transaction_amount_deposit_and_more	2026-08-31 09:55:02.751233+00
23	brokercity	0005_customer_whatsappmessage_and_more	2026-09-08 09:43:29.818306+00
24	brokercity	0006_alter_transaction_document_no_monitoring	2026-09-11 11:01:50.763398+00
25	brokercity	0007_agent_alter_monitoring_agent	2026-09-11 11:20:40.422287+00
26	brokercity	0008_monitoring_forwording_monitoring_forwording_from_and_more	2026-09-12 07:00:45.795813+00
27	brokercity	0009_monitoring_agent_lead_from	2026-09-12 07:36:03.613506+00
28	brokercity	0006_alter_transaction_document_no_and_more	2026-09-15 09:03:15.277505+00
29	brokercity	0010_alter_monitoring_agent	2026-09-16 07:20:11.100326+00
30	brokercity	0011_alter_monitoring_forwording_from_and_more	2026-09-16 07:31:42.162914+00
31	brokercity	0012_monitoring_agent_lead_phone_number	2026-09-16 07:46:39.006195+00
32	brokercity	0007_owner_category_unit	2026-09-17 07:53:34.971715+00
33	brokercity	0008_unit_owner	2026-09-17 09:24:51.989485+00
34	brokercity	0009_unit_area_unit_location	2026-09-17 11:20:31.027434+00
35	brokercity	0010_remove_unit_location_remove_unit_owner_and_more	2026-09-17 13:34:09.028579+00
36	brokercity	0011_building_alter_unit_category_delete_category	2026-09-18 06:42:17.125523+00
37	brokercity	0012_slider	2026-09-22 09:14:09.762617+00
38	brokercity	0013_rename_image_1_slider_image_remove_slider_image_2_and_more	2026-09-22 09:25:00.321839+00
39	brokercity	0014_slider_apartments_slider_area_from_and_more	2026-09-22 13:26:15.875145+00
40	brokercity	0015_unit_floor	2026-09-23 07:20:31.424672+00
41	brokercity	0016_rental	2026-09-23 08:57:55.163266+00
42	brokercity	0017_developer	2026-09-30 08:45:30.736347+00
43	brokercity	0018_transaction_subtotal_transaction_vat	2026-09-30 13:19:42.637091+00
44	brokercity	0019_offersale_paymentplan	2026-10-01 13:32:25.192452+00
45	brokercity	0020_developer_registered	2026-10-02 06:50:14.473231+00
46	brokercity	0021_monitoring	2026-10-03 07:52:19.870642+00
47	brokercity	0022_rename_monitoring_monitor	2026-10-03 07:52:22.17273+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: archive_brokercity_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: archive_brokercity_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: archive_brokercity_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: archive_brokercity_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 104, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: archive_brokercity_user
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: archive_brokercity_user
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 5, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: archive_brokercity_user
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: brokercity_account_id_seq; Type: SEQUENCE SET; Schema: public; Owner: archive_brokercity_user
--

SELECT pg_catalog.setval('public.brokercity_account_id_seq', 4, true);


--
-- Name: brokercity_accountcategory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: archive_brokercity_user
--

SELECT pg_catalog.setval('public.brokercity_accountcategory_id_seq', 2, true);


--
-- Name: brokercity_agent_id_seq; Type: SEQUENCE SET; Schema: public; Owner: archive_brokercity_user
--

SELECT pg_catalog.setval('public.brokercity_agent_id_seq', 8, true);


--
-- Name: brokercity_bank_id_seq; Type: SEQUENCE SET; Schema: public; Owner: archive_brokercity_user
--

SELECT pg_catalog.setval('public.brokercity_bank_id_seq', 2, true);


--
-- Name: brokercity_building_id_seq; Type: SEQUENCE SET; Schema: public; Owner: archive_brokercity_user
--

SELECT pg_catalog.setval('public.brokercity_building_id_seq', 2, true);


--
-- Name: brokercity_cashbox_id_seq; Type: SEQUENCE SET; Schema: public; Owner: archive_brokercity_user
--

SELECT pg_catalog.setval('public.brokercity_cashbox_id_seq', 3, true);


--
-- Name: brokercity_customer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: archive_brokercity_user
--

SELECT pg_catalog.setval('public.brokercity_customer_id_seq', 1, false);


--
-- Name: brokercity_developer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: archive_brokercity_user
--

SELECT pg_catalog.setval('public.brokercity_developer_id_seq', 12, true);


--
-- Name: brokercity_monitoring_id_seq; Type: SEQUENCE SET; Schema: public; Owner: archive_brokercity_user
--

SELECT pg_catalog.setval('public.brokercity_monitoring_id_seq', 4, true);


--
-- Name: brokercity_offersale_id_seq; Type: SEQUENCE SET; Schema: public; Owner: archive_brokercity_user
--

SELECT pg_catalog.setval('public.brokercity_offersale_id_seq', 1, false);


--
-- Name: brokercity_owner_id_seq; Type: SEQUENCE SET; Schema: public; Owner: archive_brokercity_user
--

SELECT pg_catalog.setval('public.brokercity_owner_id_seq', 3, true);


--
-- Name: brokercity_paymentplan_id_seq; Type: SEQUENCE SET; Schema: public; Owner: archive_brokercity_user
--

SELECT pg_catalog.setval('public.brokercity_paymentplan_id_seq', 1, false);


--
-- Name: brokercity_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: archive_brokercity_user
--

SELECT pg_catalog.setval('public.brokercity_profile_id_seq', 5, true);


--
-- Name: brokercity_rental_id_seq; Type: SEQUENCE SET; Schema: public; Owner: archive_brokercity_user
--

SELECT pg_catalog.setval('public.brokercity_rental_id_seq', 2, true);


--
-- Name: brokercity_slider_id_seq; Type: SEQUENCE SET; Schema: public; Owner: archive_brokercity_user
--

SELECT pg_catalog.setval('public.brokercity_slider_id_seq', 8, true);


--
-- Name: brokercity_transaction_id_seq; Type: SEQUENCE SET; Schema: public; Owner: archive_brokercity_user
--

SELECT pg_catalog.setval('public.brokercity_transaction_id_seq', 98, true);


--
-- Name: brokercity_unit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: archive_brokercity_user
--

SELECT pg_catalog.setval('public.brokercity_unit_id_seq', 3, true);


--
-- Name: brokercity_whatsappmessage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: archive_brokercity_user
--

SELECT pg_catalog.setval('public.brokercity_whatsappmessage_id_seq', 20, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: archive_brokercity_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: archive_brokercity_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 25, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: archive_brokercity_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 47, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: brokercity_account brokercity_account_pkey; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_account
    ADD CONSTRAINT brokercity_account_pkey PRIMARY KEY (id);


--
-- Name: brokercity_accountcategory brokercity_accountcategory_pkey; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_accountcategory
    ADD CONSTRAINT brokercity_accountcategory_pkey PRIMARY KEY (id);


--
-- Name: brokercity_agent brokercity_agent_phone_number_key; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_agent
    ADD CONSTRAINT brokercity_agent_phone_number_key UNIQUE (phone_number);


--
-- Name: brokercity_agent brokercity_agent_pkey; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_agent
    ADD CONSTRAINT brokercity_agent_pkey PRIMARY KEY (id);


--
-- Name: brokercity_bank brokercity_bank_name_key; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_bank
    ADD CONSTRAINT brokercity_bank_name_key UNIQUE (name);


--
-- Name: brokercity_bank brokercity_bank_pkey; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_bank
    ADD CONSTRAINT brokercity_bank_pkey PRIMARY KEY (id);


--
-- Name: brokercity_building brokercity_building_name_key; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_building
    ADD CONSTRAINT brokercity_building_name_key UNIQUE (name);


--
-- Name: brokercity_building brokercity_building_pkey; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_building
    ADD CONSTRAINT brokercity_building_pkey PRIMARY KEY (id);


--
-- Name: brokercity_cashbox brokercity_cashbox_name_key; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_cashbox
    ADD CONSTRAINT brokercity_cashbox_name_key UNIQUE (name);


--
-- Name: brokercity_cashbox brokercity_cashbox_pkey; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_cashbox
    ADD CONSTRAINT brokercity_cashbox_pkey PRIMARY KEY (id);


--
-- Name: brokercity_customer brokercity_customer_phone_number_key; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_customer
    ADD CONSTRAINT brokercity_customer_phone_number_key UNIQUE (phone_number);


--
-- Name: brokercity_customer brokercity_customer_pkey; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_customer
    ADD CONSTRAINT brokercity_customer_pkey PRIMARY KEY (id);


--
-- Name: brokercity_developer brokercity_developer_pkey; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_developer
    ADD CONSTRAINT brokercity_developer_pkey PRIMARY KEY (id);


--
-- Name: brokercity_monitor brokercity_monitoring_pkey; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_monitor
    ADD CONSTRAINT brokercity_monitoring_pkey PRIMARY KEY (id);


--
-- Name: brokercity_offersale brokercity_offersale_pkey; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_offersale
    ADD CONSTRAINT brokercity_offersale_pkey PRIMARY KEY (id);


--
-- Name: brokercity_offersale brokercity_offersale_unit_no_key; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_offersale
    ADD CONSTRAINT brokercity_offersale_unit_no_key UNIQUE (unit_no);


--
-- Name: brokercity_owner brokercity_owner_name_key; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_owner
    ADD CONSTRAINT brokercity_owner_name_key UNIQUE (name);


--
-- Name: brokercity_owner brokercity_owner_phone_key; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_owner
    ADD CONSTRAINT brokercity_owner_phone_key UNIQUE (phone);


--
-- Name: brokercity_owner brokercity_owner_pkey; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_owner
    ADD CONSTRAINT brokercity_owner_pkey PRIMARY KEY (id);


--
-- Name: brokercity_paymentplan brokercity_paymentplan_pkey; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_paymentplan
    ADD CONSTRAINT brokercity_paymentplan_pkey PRIMARY KEY (id);


--
-- Name: brokercity_profile brokercity_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_profile
    ADD CONSTRAINT brokercity_profile_pkey PRIMARY KEY (id);


--
-- Name: brokercity_profile brokercity_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_profile
    ADD CONSTRAINT brokercity_profile_user_id_key UNIQUE (user_id);


--
-- Name: brokercity_rental brokercity_rental_pkey; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_rental
    ADD CONSTRAINT brokercity_rental_pkey PRIMARY KEY (id);


--
-- Name: brokercity_slider brokercity_slider_pkey; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_slider
    ADD CONSTRAINT brokercity_slider_pkey PRIMARY KEY (id);


--
-- Name: brokercity_transaction brokercity_transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_transaction
    ADD CONSTRAINT brokercity_transaction_pkey PRIMARY KEY (id);


--
-- Name: brokercity_transaction brokercity_transaction_transaction_no_key; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_transaction
    ADD CONSTRAINT brokercity_transaction_transaction_no_key UNIQUE (transaction_no);


--
-- Name: brokercity_unit brokercity_unit_name_key; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_unit
    ADD CONSTRAINT brokercity_unit_name_key UNIQUE (name);


--
-- Name: brokercity_unit brokercity_unit_pkey; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_unit
    ADD CONSTRAINT brokercity_unit_pkey PRIMARY KEY (id);


--
-- Name: brokercity_whatsappmessage brokercity_whatsappmessage_pkey; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_whatsappmessage
    ADD CONSTRAINT brokercity_whatsappmessage_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: brokercity_account_category_id_9f0b168e; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX brokercity_account_category_id_9f0b168e ON public.brokercity_account USING btree (category_id);


--
-- Name: brokercity_agent_phone_number_ce78e83a_like; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX brokercity_agent_phone_number_ce78e83a_like ON public.brokercity_agent USING btree (phone_number varchar_pattern_ops);


--
-- Name: brokercity_bank_name_1a91b433_like; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX brokercity_bank_name_1a91b433_like ON public.brokercity_bank USING btree (name varchar_pattern_ops);


--
-- Name: brokercity_building_name_d342dfab_like; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX brokercity_building_name_d342dfab_like ON public.brokercity_building USING btree (name varchar_pattern_ops);


--
-- Name: brokercity_building_owner_id_08d1a351; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX brokercity_building_owner_id_08d1a351 ON public.brokercity_building USING btree (owner_id);


--
-- Name: brokercity_cashbox_name_9f74b628_like; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX brokercity_cashbox_name_9f74b628_like ON public.brokercity_cashbox USING btree (name varchar_pattern_ops);


--
-- Name: brokercity_customer_phone_number_373b4cb7_like; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX brokercity_customer_phone_number_373b4cb7_like ON public.brokercity_customer USING btree (phone_number varchar_pattern_ops);


--
-- Name: brokercity_offersale_unit_no_4ee0aeea_like; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX brokercity_offersale_unit_no_4ee0aeea_like ON public.brokercity_offersale USING btree (unit_no varchar_pattern_ops);


--
-- Name: brokercity_owner_address_f0ae9f8e; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX brokercity_owner_address_f0ae9f8e ON public.brokercity_owner USING btree (address);


--
-- Name: brokercity_owner_address_f0ae9f8e_like; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX brokercity_owner_address_f0ae9f8e_like ON public.brokercity_owner USING btree (address varchar_pattern_ops);


--
-- Name: brokercity_owner_name_3f5df40b_like; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX brokercity_owner_name_3f5df40b_like ON public.brokercity_owner USING btree (name varchar_pattern_ops);


--
-- Name: brokercity_owner_phone_1b697abc_like; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX brokercity_owner_phone_1b697abc_like ON public.brokercity_owner USING btree (phone varchar_pattern_ops);


--
-- Name: brokercity_paymentplan_unit_no_2edddf89; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX brokercity_paymentplan_unit_no_2edddf89 ON public.brokercity_paymentplan USING btree (unit_no);


--
-- Name: brokercity_paymentplan_unit_no_2edddf89_like; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX brokercity_paymentplan_unit_no_2edddf89_like ON public.brokercity_paymentplan USING btree (unit_no varchar_pattern_ops);


--
-- Name: brokercity_transaction_bank_id_0c0601bd; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX brokercity_transaction_bank_id_0c0601bd ON public.brokercity_transaction USING btree (bank_id);


--
-- Name: brokercity_transaction_cashbox_id_fd679a6e; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX brokercity_transaction_cashbox_id_fd679a6e ON public.brokercity_transaction USING btree (cashbox_id);


--
-- Name: brokercity_transaction_transaction_no_d4c4121d_like; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX brokercity_transaction_transaction_no_d4c4121d_like ON public.brokercity_transaction USING btree (transaction_no varchar_pattern_ops);


--
-- Name: brokercity_transaction_transaction_user_id_dec25f52; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX brokercity_transaction_transaction_user_id_dec25f52 ON public.brokercity_transaction USING btree (transaction_user_id);


--
-- Name: brokercity_unit_area_fe3ff1f9; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX brokercity_unit_area_fe3ff1f9 ON public.brokercity_unit USING btree (area);


--
-- Name: brokercity_unit_area_fe3ff1f9_like; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX brokercity_unit_area_fe3ff1f9_like ON public.brokercity_unit USING btree (area varchar_pattern_ops);


--
-- Name: brokercity_unit_category_id_f27b2cda; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX brokercity_unit_category_id_f27b2cda ON public.brokercity_unit USING btree (category_id);


--
-- Name: brokercity_unit_name_fefca5c5_like; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX brokercity_unit_name_fefca5c5_like ON public.brokercity_unit USING btree (name varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: archive_brokercity_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: brokercity_account brokercity_account_category_id_9f0b168e_fk_brokercit; Type: FK CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_account
    ADD CONSTRAINT brokercity_account_category_id_9f0b168e_fk_brokercit FOREIGN KEY (category_id) REFERENCES public.brokercity_accountcategory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: brokercity_building brokercity_building_owner_id_08d1a351_fk_brokercity_owner_id; Type: FK CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_building
    ADD CONSTRAINT brokercity_building_owner_id_08d1a351_fk_brokercity_owner_id FOREIGN KEY (owner_id) REFERENCES public.brokercity_owner(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: brokercity_paymentplan brokercity_paymentpl_unit_no_2edddf89_fk_brokercit; Type: FK CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_paymentplan
    ADD CONSTRAINT brokercity_paymentpl_unit_no_2edddf89_fk_brokercit FOREIGN KEY (unit_no) REFERENCES public.brokercity_offersale(unit_no) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: brokercity_profile brokercity_profile_user_id_4f6b81f9_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_profile
    ADD CONSTRAINT brokercity_profile_user_id_4f6b81f9_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: brokercity_transaction brokercity_transacti_cashbox_id_fd679a6e_fk_brokercit; Type: FK CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_transaction
    ADD CONSTRAINT brokercity_transacti_cashbox_id_fd679a6e_fk_brokercit FOREIGN KEY (cashbox_id) REFERENCES public.brokercity_cashbox(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: brokercity_transaction brokercity_transacti_transaction_user_id_dec25f52_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_transaction
    ADD CONSTRAINT brokercity_transacti_transaction_user_id_dec25f52_fk_auth_user FOREIGN KEY (transaction_user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: brokercity_transaction brokercity_transaction_bank_id_0c0601bd_fk_brokercity_bank_id; Type: FK CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_transaction
    ADD CONSTRAINT brokercity_transaction_bank_id_0c0601bd_fk_brokercity_bank_id FOREIGN KEY (bank_id) REFERENCES public.brokercity_bank(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: brokercity_unit brokercity_unit_category_id_f27b2cda_fk_brokercity_building_id; Type: FK CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.brokercity_unit
    ADD CONSTRAINT brokercity_unit_category_id_f27b2cda_fk_brokercity_building_id FOREIGN KEY (category_id) REFERENCES public.brokercity_building(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: archive_brokercity_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: archive_brokercity_user
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON SEQUENCES TO archive_brokercity_user;


--
-- Name: DEFAULT PRIVILEGES FOR TYPES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TYPES TO archive_brokercity_user;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON FUNCTIONS TO archive_brokercity_user;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TABLES TO archive_brokercity_user;


--
-- PostgreSQL database dump complete
--

\unrestrict 7wAUWHN9oVdahlRyvHDkpvC2HHkXHWfYscZP6l6kRJ67wPWqHfiXHijy1M9OvCg

